[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

; 串口监视器与上传速率配置
monitor_speed = 115200
upload_speed = 115200

; 编译选项：增加最大 MQTT 数据包大小为 65536 字节（64KB）以支持传输 JPEG 图片
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DMQTT_MAX_PACKET_SIZE=60000

; 上传与调试协议配置
upload_protocol = esptool
monitor_filters = direct

lib_deps =
    knolleary/PubSubClient @ ^2.8
